name: Deploy Delichat FE

on:
  push:
    branches:
      - developer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22

          script: |
            set -e
            
            echo "Đi vào thư mục project fe"
            cd ~/deli-social-fe
            
            echo "Cập nhật code nhánh developer"
            git pull origin developer
            
            disown

            echo "✅ Deploy backend account-service hoàn tất!"

